[WIP] Fix #5458
This is intended to fix the simulator and add appropriate tests.
However, it looks like there is some confusion around the handling of
NaNs in the atomic max and min cases. Some of the tests fail on the
hardware:

$ python -m numba.runtests numba.cuda.tests.cudapy.test_atomics
........................F........FF..
======================================================================
FAIL: test_atomic_max_returns_old_nan_in_array (numba.cuda.tests.cudapy.test_atomics.TestCudaAtomics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_atomics.py", line 476, in test_atomic_max_returns_old_nan_in_array
    self._test_atomic_returns_old(kernel, np.nan)
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_atomics.py", line 455, in _test_atomic_returns_old
    self.assertEqual(x[1], initial)
AssertionError: 1.0 != nan

======================================================================
FAIL: test_atomic_min_returns_old_nan_in_array (numba.cuda.tests.cudapy.test_atomics.TestCudaAtomics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_atomics.py", line 497, in test_atomic_min_returns_old_nan_in_array
    self._test_atomic_returns_old(kernel, np.nan)
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_atomics.py", line 455, in _test_atomic_returns_old
    self.assertEqual(x[1], initial)
AssertionError: 11.0 != nan

======================================================================
FAIL: test_atomic_min_returns_old_nan_val (numba.cuda.tests.cudapy.test_atomics.TestCudaAtomics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_atomics.py", line 504, in test_atomic_min_returns_old_nan_val
    self._test_atomic_returns_old(kernel, np.nan)
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_atomics.py", line 455, in _test_atomic_returns_old
    self.assertEqual(x[1], initial)
AssertionError: 11.0 != nan

----------------------------------------------------------------------
Ran 37 tests in 2.181s

FAILED (failures=3)

This may be due to an error in the tests, the documentation, or the
implementation - I have yet to determine which.